version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: local-tws-school
    ports:
      - 3306:3306
    environment:
      - LANG=C.UTF-8
      - TERM=dumb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ProgramCenter
networks:
  main: