export const STUDENT_MODIFY_ASSIGNMENT_STATUS = 'STUDENT_MODIFY_ASSIGNMENT_STATUS'
export const TUTOR_MODIFY_ASSIGNMENT_STATUS = 'TUTOR_MODIFY_ASSIGNMENT_STATUS'
export const TUTOR_COMMENT_ASSIGNMENT = 'TUTOR_COMMENT_ASSIGNMENT'
export const STUDENT_COMMENT_ASSIGNMENT = 'STUDENT_COMMENT_ASSIGNMENT'
