export const INIT_USER = 'INIT_USER'
export const GET_SETTINGS = 'GET_SETTINGS'
export const REFRESH_NOTIFICATIONS = 'REFRESH_NOTIFICATIONS'
export const REFRESH_CONTACT_USERS = 'REFRESH_CONTACT_USERS'
