export const GROWTH_NOTE_STUDENT_TO_TUTOR = 'GROWTH_NOTE_STUDENT_TO_TUTOR'
export const GROWTH_NOTE_TUTOR_TO_STUDENT = 'GROWTH_NOTE_TUTOR_TO_STUDENT'
export const GROWTH_EXCELLENT_NOTE = 'GROWTH_EXCELLENT_NOTE'
