kind: Deployment
apiVersion: apps/v1
metadata:
  name: tws-bootcamp-center-web
  namespace: APP_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: tws-bootcamp-center-web
  template:
    metadata:
      namespace: APP_NAMESPACE
      labels:
        k8s-app: tws-bootcamp-center-web
    spec:
      imagePullSecrets:
      - name: IMAGE_PULL_SECRETS
      containers:
      - image: 52.81.18.101/tws/tws-bootcamp-center-web:DOCKER_VERSION
        name: tws-bootcamp-center-web
        env:
        - name: APP_VERSION
          value: DOCKER_VERSION
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  namespace: APP_NAMESPACE
  name: tws-bootcamp-center-web
spec:
  selector:
    k8s-app: tws-bootcamp-center-web
  ports:
  - name: nginx
    port: 80
    protocol: TCP