version: "3.3"
services:
  jenkins-alpine:
    image: harbor.thoughtworks-school.com/tws/jenkins:2.60.3-V11
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker